# Generated by Django 2.0.9 on 2018-10-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20181018_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='creaotr',
            new_name='creator',
        ),
    ]
