# Generated by Django 2.0.9 on 2019-03-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20190302_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
