# Generated by Django 2.0.9 on 2018-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181021_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not-specified', 'Not specified')], max_length=80, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=140, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(null=True, verbose_name='website'),
        ),
    ]
